# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/mapper/luks-7ab4c07b-bba5-4b40-ba61-ea131d3947bb";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-7ab4c07b-bba5-4b40-ba61-ea131d3947bb".device = "/dev/disk/by-uuid/7ab4c07b-bba5-4b40-ba61-ea131d3947bb";

  fileSystems."/home" =
    {
      device = "/dev/mapper/luks-7ab4c07b-bba5-4b40-ba61-ea131d3947bb";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/mapper/luks-7ab4c07b-bba5-4b40-ba61-ea131d3947bb";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/761E-EE02";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
