# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-a0b64bdf-b5b7-4bcb-9bc1-f5d4a9d49313";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-a0b64bdf-b5b7-4bcb-9bc1-f5d4a9d49313".device = "/dev/disk/by-uuid/a0b64bdf-b5b7-4bcb-9bc1-f5d4a9d49313";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-a0b64bdf-b5b7-4bcb-9bc1-f5d4a9d49313";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-a0b64bdf-b5b7-4bcb-9bc1-f5d4a9d49313";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4EFE-7614";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
