#outputs = { Targets = ["eDP-1"] }
[modules]
left = [ "Workspaces" ]
center = [ ["Tempo"] ]
right = [ ["Tray", "SystemInfo",  "Privacy", "Settings" ] ]
[tempo]
clock_format = "%a %d %b %R"
weather_location = { City = "Mestre" }
weather_indicator = "IconAndTemperature"
[appearance]
style = "Gradient"
font_name = "JetBrainsMono Nerd Font"
# scale_factor = 1.5
[system_info]
indicators = ["Cpu", "Memory", "Temperature"]
interval = 1
[system_info.temperature]
warn_threshold = 70
alert_threshold = 85
